### PR TITLE
[bugfix]: avoid checkpoint when replay in large result mode

### LINKED ISSUE #338: [Bug]: Duplicate SUCCEEDED checkpoint when handling large result in MAP operation
### Expected Behavior

checkpoint of SUCCEEDED map operation is called only once

### Actual Behavior

checkpoint is called again when replay map operations for large result, causing the call to fail

### Steps to Reproduce

run the test case `testMapWithLargeResult_replayChildren` and observe the history events.

### SDK Version

1.0.1

### Java Version

17

### Is this a regression?

No

### Last Working Version

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zhongkechen**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### Issue Link, if available

Fixes https://github.com/aws/aws-durable-execution-sdk-java/issues/338

### Description

When the map operation is replayed with large result, it checkpoints the result again even if the operation has already succeeded. 

Fix:
Skip checkpoint if the operation is completed. 

### Checklist

- [x] I have filled out every section of the PR template
- [x] I have thoroughly tested this change

#### Unit Tests

Have unit tests been written for these changes?

#### Integration Tests

Have integration tests been written for these changes?

#### Examples

Has a new example been added for the change? (if applicable)

### CODE REVIEW

**Review by wangyb-A — APPROVED** [review]

File: sdk-integration-tests/src/test/java/software/amazon/lambda/durable/MapIntegrationTest.java [hunk 1]
```diff
@@ -862,12 +862,14 @@ void testMapWithLargeResult_replayChildren() {
...
         var result1 = runner.runUntilComplete("test");
         assertEquals(ExecutionStatus.SUCCEEDED, result1.getStatus());
+        assertEquals(202, result1.getHistoryEvents().size());
         var firstRunCount = executionCount.get();
         assertTrue(firstRunCount >= 100);
 
         // Replay — large result path: replayChildren=true, children replay from cache
         var result2 = runner.run("test");
         assertEquals(ExecutionStatus.SUCCEEDED, result2.getStatus());
+        assertEquals(202, result2.getHistoryEvents().size());
```
Comment (zhongkechen) [inline sdk-integration-tests/src/test/java/software/amazon/lambda/durable/MapIntegrationTest.java:872]: Was 203 without this bug fix

**Review by ayushiahjolia — APPROVED** [review]
