### PR TITLE
bugfix: fix thread synchronization and add some complex parallel tests 

### LINKED ISSUE #301: [Bug]: stuck executions with parallel/map operation
### Expected Behavior

The executions with map and parallel always make progresses when branches complete

### Actual Behavior

The test cases from this PR sometimes get stuck:
https://github.com/aws/aws-durable-execution-sdk-java/pull/284

### Steps to Reproduce
[SilanHe edits]
If you run this many times in your IDE, you can easily reproduce this for the "stuck" case. I'm using IntelliJ and breakpointing the SDK code where it's "registering" and "deregistering" the code. In the slower debugger environment, the code breaks down and often is stuck with child context threads unable to proceed.

### SDK Version

1.0.0

### Java Version

17

### Is this a regression?

No

### Last Working Version

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by wangyb-A**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### Issue Link, if available

- Fix: #301 
- #262 

### Description

- fix the race condition #301 
   - check the details of the bug here: https://github.com/aws/aws-durable-execution-sdk-java/issues/301#issuecomment-4261885070 
- **Add parallel complex tests**
- add a test dependency on log4j to enable logging for integration tests

### Checklist

- [x] I have filled out every section of the PR template
- [x] I have thoroughly tested this change

#### Unit Tests

Have unit tests been written for these changes? Updated

#### Integration Tests

Have integration tests been written for these changes? Added

#### Examples

Has a new example been added for the change? (if applicable)

### CODE REVIEW

File: sdk/src/main/java/software/amazon/lambda/durable/operation/BaseDurableOperation.java [hunk 1]
```diff
@@ -210,7 +221,7 @@ protected Operation waitForOperationCompletion() {
 
         // Block until operation completes. No-op if the future is already completed.
         try {
-            completionFuture.join();
+            future.join();
```
Comment (SilanHe) [inline sdk/src/main/java/software/amazon/lambda/durable/operation/BaseDurableOperation.java:224]: nice, this is such a sneaky bug

Comment (wangyb-A) [inline sdk/src/main/java/software/amazon/lambda/durable/operation/BaseDurableOperation.java:224]: this gaurantee join() happen after `registerActiveThread`

File: sdk-integration-tests/src/test/java/software/amazon/lambda/durable/ParallelIntegrationTest.java [hunk 2]
```diff
@@ -637,4 +1035,35 @@ void testParallelWithAllSuccessful_stopsOnFirstFailure() {
...
+                    parallel.branch("branch-" + item, String.class, ctx -> item.toUpperCase());
+                }
+            }
+
+            var result = parallel.get();
+            assertEquals(ConcurrencyCompletionStatus.MIN_SUCCESSFUL_REACHED, result.completionStatus());
+            assertTrue(result.completionStatus().isSucceeded());
+            // todo: the result is constructed when handling parallel completion,
+            // which might be earlier than the last branch is added.
+            assertTrue(3 >= result.size());
```
Comment (SilanHe) [inline sdk-integration-tests/src/test/java/software/amazon/lambda/durable/ParallelIntegrationTest.java]: don't we need to change this assert technically? couldn't result size could be 1-3

Similar to this PR: https://github.com/aws/aws-durable-execution-sdk-java/pull/315/changes

File: sdk/src/main/java/software/amazon/lambda/durable/operation/BaseDurableOperation.java [hunk 3]
```diff
@@ -182,6 +182,7 @@ protected Operation waitForOperationCompletion() {
         validateCurrentThreadType();
 
         var threadContext = getCurrentThreadContext();
+        CompletableFuture<?> future = completionFuture;
```
Comment (SilanHe) [inline sdk/src/main/java/software/amazon/lambda/durable/operation/BaseDurableOperation.java:185]: nit: might have been cleaner to just do a separate PR for the bug fix

File: sdk-integration-tests/src/test/java/software/amazon/lambda/durable/ParallelIntegrationTest.java (hunk 2 above)
Comment (zhongkechen) [reply sdk-integration-tests/src/test/java/software/amazon/lambda/durable/ParallelIntegrationTest.java]: I think I could chain both assertions together

File: sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java [hunk 4]
```diff
@@ -255,7 +255,10 @@ private BaseDurableOperation waitForChildCompletion(
             future = CompletableFuture.anyOf(futures.toArray(CompletableFuture[]::new));
             // skip deregistering the current thread if there is more completed future to process
             if (!future.isDone()) {
-                future.thenRun(() -> registerActiveThread(threadContext.threadId()));
+                future = future.thenApply(o -> {
+                    registerActiveThread(threadContext.threadId());
+                    return o;
+                });
```
Comment (wangyb-A) [inline sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java:261]: just curious why we use thenApply than thenReturn here?

File: sdk/src/main/java/software/amazon/lambda/durable/operation/BaseDurableOperation.java (hunk 1 above)
Comment (zhongkechen) [reply sdk/src/main/java/software/amazon/lambda/durable/operation/BaseDurableOperation.java:224]: Yes, because this `join` is chained after `thenRun`, not the original `completionFuture`

File: sdk/src/main/java/software/amazon/lambda/durable/operation/BaseDurableOperation.java (hunk 3 above)
Comment (zhongkechen) [reply sdk/src/main/java/software/amazon/lambda/durable/operation/BaseDurableOperation.java:185]: Yeah, reused this PR to make sure the fix works on the cloud with the new test cases

File: sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java (hunk 4 above)
Comment (zhongkechen) [reply sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java:261]: So the `join()` below can receive the result. We rely on that to determine which branch is completed.

File: sdk-integration-tests/src/test/java/software/amazon/lambda/durable/ParallelIntegrationTest.java (hunk 2 above)
Comment (zhongkechen) [reply sdk-integration-tests/src/test/java/software/amazon/lambda/durable/ParallelIntegrationTest.java]: Updated

**Review by zhongkechen — APPROVED** [review]

**Review by SilanHe — APPROVED** [review]

File: sdk-integration-tests/src/test/java/software/amazon/lambda/durable/ParallelIntegrationTest.java (hunk 2 above)
Comment (zhongkechen) [reply sdk-integration-tests/src/test/java/software/amazon/lambda/durable/ParallelIntegrationTest.java]: Created an issue for this: https://github.com/aws/aws-durable-execution-sdk-java/issues/332
