### PR TITLE
[bugfix]: fix inconsistency result when replay concurrency operations

### LINKED ISSUE #344: [Bug]: inconsistent result when replaying concurrency operations
Two concurrency operation result consistent issues during replay

1. Branches/items that are skipped (neither succeeded nor failed ones) when checkpointing the results, could succeed or fail during replay. This occurs when a parallel operation or a map operation with large results has early termination conditions (min successful or max failure tolerant) and the items/branches are completed with an inconsistent order during replay. 

2. Branches/items that succeeded or failed when checkpointing the results, could be skipped during replay. This occurs when a parallel operation or a map operation with large results has early termination conditions (min successful or max failure tolerant) and more branches than specified condition are completed due to concurrency.

### PR DESCRIPTION
**Pull request by zhongkechen**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### Issue Link, if available

Fixes: #344 

### Description

Two concurrency operation result consistent issues during replay

1. Branches/items that are skipped (neither succeeded nor failed ones) when checkpointing the results, could succeed or fail during replay. This occurs when a parallel operation or a map operation with large results has early termination conditions (min successful or max failure tolerant) and the items/branches are completed with an inconsistent order during replay. 

2. Branches/items that succeeded or failed when checkpointing the results, could be skipped during replay. This occurs when a parallel operation or a map operation with large results has early termination conditions (min successful or max failure tolerant) and more branches than specified condition are completed due to concurrency.
 
Fixes:

1. always checkpoint the status of each branch/item in the concurrency operation's result
2. skip the items/branches with SKIPPED status during replay
4. always wait until checkpointed succeeded/failed branches/items to complete during replay

### Checklist

- [x] I have filled out every section of the PR template
- [x] I have thoroughly tested this change

#### Unit Tests

Have unit tests been written for these changes? Yes

#### Integration Tests

Have integration tests been written for these changes? Yes

#### Examples

Has a new example been added for the change? (if applicable)

### CODE REVIEW

**Comment by SilanHe** [comment]
just for me, could you elaborate on what the fix is?

> Fixed issues in replaying concurrency operations
> 
> skip the items/branches previously skipped to prevent a race condition that the skipped branches could succeed/fail
> always wait until previously succeeded/failed branches to complete to prevent a race condition that the previously completed branches could be skipped

I'm having trouble understanding what this means

**Comment by zhongkechen** [comment]
> just for me, could you elaborate on what the fix is?
> 
> > Fixed issues in replaying concurrency operations
> > skip the items/branches previously skipped to prevent a race condition that the skipped branches could succeed/fail
> > always wait until previously succeeded/failed branches to complete to prevent a race condition that the previously completed branches could be skipped
> 
> I'm having trouble understanding what this means

Updated description of the PR. Hope it's easier to understand.

File: sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java [hunk 1]
```diff
@@ -129,21 +131,24 @@ protected <R> ChildContextOperation<R> createItem(
...
             SerDes serDes,
-            OperationSubType branchSubType) {
+            OperationSubType branchSubType,
+            boolean skipped) {
         var operationId = this.operationIdGenerator.nextOperationId();
         var childOp = createItem(operationId, name, function, resultType, serDes, branchSubType);
         branches.add(childOp);
-        pendingQueue.add(childOp);
-        logger.debug("Item enqueued {}", name);
+        if (!skipped) {
```
Comment (SilanHe) [inline sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java:148]: why even call enqueueItem if we're going to skip it anyway. Wouldn't this future never resolve?

File: sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java [hunk 2]
```diff
@@ -302,10 +317,22 @@ private void onItemComplete(
...
-            AtomicInteger succeededCount, AtomicInteger failedCount, Set<BaseDurableOperation> runningChildren) {
+            AtomicInteger succeededCount,
+            AtomicInteger failedCount,
+            Set<BaseDurableOperation> runningChildren,
+            ExpectedCompletionStatus expectedCompletionStatus) {
         int succeeded = succeededCount.get();
         int failed = failedCount.get();
 
+        if (expectedCompletionStatus != null) {
+            if (succeeded + failed >= expectedCompletionStatus.completed) {
```
Comment (SilanHe) [inline sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java:328]: what is this check for?

File: sdk/src/main/java/software/amazon/lambda/durable/operation/MapOperation.java [hunk 3]
```diff
@@ -72,24 +70,31 @@ public MapOperation(
...
     }
 
     private void addAllItems() {
-        // Enqueue all items first, then start execution. This prevents early termination
-        // criteria (e.g., minSuccessful) from completing the operation mid-loop on replay,
-        // which would cause subsequent enqueue calls to fail with "completed operation".
+        addAllItemsWithStatus(Collections.nCopies(items.size(), null));
+    }
+
+    private void addAllItemsWithStatus(List<MapResult.MapResultItem.Status> resultItems) {
```
Comment (SilanHe) [inline sdk/src/main/java/software/amazon/lambda/durable/operation/MapOperation.java]: is the goal of this function to enqueue all items with `status != MapResult.MapResultItem.Status.SKIPPED`?

perhaps, we can name this `addAllUnskippedItems` or something more descriptive

File: sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java (hunk 1 above)
Comment (zhongkechen) [reply sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java:148]: `branches` will have the skipped items. We skip `pendingQueue` so that the skipped items will not be executed.

File: sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java (hunk 2 above)
Comment (zhongkechen) [reply sdk/src/main/java/software/amazon/lambda/durable/operation/ConcurrencyOperation.java:328]: To make sure all succeeded/failed items/branches will succeed/fail in replay.

File: sdk/src/main/java/software/amazon/lambda/durable/operation/MapOperation.java (hunk 3 above)
Comment (zhongkechen) [reply sdk/src/main/java/software/amazon/lambda/durable/operation/MapOperation.java]: Yeah, sounds good

File: sdk/src/main/java/software/amazon/lambda/durable/operation/ParallelOperation.java [hunk 4]
```diff
@@ -67,44 +67,45 @@ public ParallelOperation(
...
+                .count());
         int failedCount = Math.toIntExact(
-                items.stream().filter(this::isOperationCompletedExceptionally).count());
-        this.cachedResult = new ParallelResult(items.size(), succeededCount, failedCount, concurrencyCompletionStatus);
-        if (skipCheckpoint) {
-            // Do not send checkpoint during replay
-            markAlreadyCompleted();
-            return;
-        }
+                statuses.stream().filter(s -> s == ParallelResult.Status.FAILED).count());
```
Comment (SilanHe) [inline sdk/src/main/java/software/amazon/lambda/durable/operation/ParallelOperation.java:75]: nit: `succeededCount` is formatted differently from  `failedCount`

Comment (zhongkechen) [reply sdk/src/main/java/software/amazon/lambda/durable/operation/ParallelOperation.java:75]: This is out of my control. `spotless` controls every aspect of formatting

File: sdk-integration-tests/src/test/java/software/amazon/lambda/durable/MapIntegrationTest.java [hunk 5]
```diff
@@ -1003,6 +1004,130 @@ void testMapWithMinSuccessful_replay(NestingType nestingType, int events) {
...
+                        return item.toUpperCase().repeat(1000000);
+                    },
+                    config);
+
+            // always the same items get skipped when replay
+            if (initialResult.get() == null) {
+                initialResult.set(result);
+            } else {
+                assertEquals(initialResult.get(), result);
+            }
```
Comment (SilanHe) [inline sdk-integration-tests/src/test/java/software/amazon/lambda/durable/MapIntegrationTest.java:1102]: what does this do?

Comment (SilanHe) [reply sdk-integration-tests/src/test/java/software/amazon/lambda/durable/MapIntegrationTest.java:1102]: nvm I just saw this variable is declared outside of the DurableHandler.

**Review by yaythomas — APPROVED** [review]
